### PR TITLE
Finished Using Bootstrap Project - Microverse - Development Branch

### PR DESCRIPTION
**Pull request by Dandush03**
Miising Fixed Nav, Since it gets resized with some JS function that I still don't know how to use
Looking forward for this branch approvals.
Thanks for your time.

### CODE REVIEW

**Review by pelzolga123 — COMMENTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Daniel!  
### Your project looks :+1: amazing!
Here are the changes, you need to make, before this project can be approved:
* [x] One section is missing:
image
* [x] In tablet mode `Opinion` and `Latest news` sections should look more like original(smaller pictures, more padding where needed):
image
 Original:
image
* [x] Same changes are required for `In the magazine` and `Editors pick` sections in tablet mode. They should look more like original:
image
image
Original:
image
image
* [ ] Next parts require some minor changes in mobile version, to look more like original:
image
image
image
Original:
image
image
image

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by Dandush03** [comment]
Updated Project with the requested changes

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴

Hi @Dandush03, that is great work. 👍  Keep up. Before we can approve this project, we need to make changes to the project. Find comments below: ✈️ 
- In tablet mode, currently, in the Editors Pick this is how it looks
edi-4-c
```Original```
ed-2-c
- Let us add ```padding``` to ```Newsweek Conversation``` layout
newsw
- Currently in ```tablet mode```
ctab1
```Original```
tab1
- On ``` mobile mode``` let us add ```padding``` to Newsweek Conversation.
mob-sc

Kindly make these changes and submit another code review 😄 
Happy coding 💻 
Daniel Larbi Addo

**Comment by Dandush03** [comment]
Updated Project with the requested changes thanks for the review

**Comment by kobiyoyo** [comment]
## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @Dandush03    
#### Great Job so far, fixing errors from previous review.
#### Page Structure 
#### Navigation
- [x] Your navbar in tablet mode should look similar to the original
### Original Version



### Your Version



 Make changes and submit another code review request.
*Happy coding*

**Comment by Dandush03** [comment]
done, thanks for that review.

**Review by rOluochKe — APPROVED** [review]
Hello @Dandush03 

### Following previous reviews and seeing you have made required changes. The project looks good.
### Congratulations for the good job done :clap: :boom: I approve.
### You can merge and submit a project completion form from your dashboard.
- I wish you the best in the next project.
- Happy coding!

**Pull request merged**
